import type { Catalog } from "./i18n";

/** Spanish overlay for menus, settings, and native dialogs. Missing keys stay English. */
export const catalogEs: Catalog = {
  "settings.title": "&Ajustes",
  "settings.title_mac": "&Preferencias",
  "settings.theme": "Apariencia",
  "settings.theme.system": "Sistema",
  "settings.theme.light": "Claro",
  "settings.theme.dark": "Oscuro",
  "settings.density": "Densidad",
  "settings.density.default": "Predeterminada",
  "settings.density.comfortable": "Cómoda",
  "settings.density.compact": "Compacta",
  "settings.custom_tray": "Icono de bandeja personalizado (PNG)…",
  "settings.custom_tray_clear": "Usar el icono incluido",
  "settings.badge_color": "Color del distintivo no leído",
  "settings.badge_red": "Rojo",
  "settings.badge_accent": "Acento (sin punto rojo)",
  "settings.mica": "Barra Mica de Windows 11 (reinicio)",
  "settings.mute_hotkey": "Silencio global (Ctrl+Shift+M)",
  "settings.profile": "Perfil de cuenta (reinicio)",
  "settings.profile.main": "Principal",
  "settings.profile.work": "Trabajo",
  "settings.profile.personal": "Personal",
  "settings.profile.guest": "Invitado (se borra al salir)",
  "settings.snippet_copy_1": "Copiar fragmento 1",
  "settings.snippet_copy_2": "Copiar fragmento 2",
  "settings.snippet_copy_3": "Copiar fragmento 3",
  "settings.snippet_save_1": "Guardar portapapeles como fragmento 1",
  "settings.snippet_save_2": "Guardar portapapeles como fragmento 2",
  "settings.snippet_save_3": "Guardar portapapeles como fragmento 3",
  "settings.signature_save": "Guardar portapapeles como firma de protocolo",
  "settings.confirm_protocol": "Confirmar antes de redactar desde un enlace",
  "settings.mute_toast_clipboard": "Silenciar toasts del SO para el nombre del portapapeles (no el silencio de Google)",
  "settings.auto_hide_menu": "Ocultar la barra de menú automáticamente",
  "settings.tray": "Mostrar icono en la bandeja",
  "settings.tray_mac": "Mostrar icono en la barra de menús",
  "settings.start_in_tray": "Iniciar en la bandeja",
  "settings.start_hidden": "Iniciar oculto",
  "settings.mono_tray": "Icono de bandeja en monocromo",
  "settings.tray_icons": "Mostrar iconos en el menú de la bandeja",
  "settings.red_dot": "Punto rojo para mensajes no leídos",
  "settings.hide_content": "Ocultar el contenido de las notificaciones",
  "settings.notify_sound": "Sonido de notificación",
  "settings.quiet_hours": "Horas silenciosas",
  "settings.quiet_hours.off": "Desactivado",
  "settings.always_on_top": "Siempre visible",
  "settings.reduce_motion": "Reducir movimiento (sin parpadeo de la barra de tareas)",
  "settings.close_behavior": "Al cerrar la ventana",
  "settings.close_ask": "Preguntar cada vez",
  "settings.close_tray": "Minimizar a la bandeja",
  "settings.close_quit": "Salir de la aplicación",
  "settings.hw_accel": "Aceleración por hardware (requiere reinicio)",
  "settings.reset_window": "Restablecer tamaño y posición",
  "settings.taskbar_flash": "Parpadear la barra de tareas ante un mensaje nuevo",
  "settings.spellcheck": "Corrector ortográfico",
  "settings.save_crashes": "Guardar detalles de bloqueo para revisarlos",
  "settings.check_updates_launch": "Buscar actualizaciones al iniciar",
  "settings.start_with_os": "Iniciar con el sistema operativo",
  "settings.user_css": "Cargar user.css local (nunca remoto)",
  "settings.user_css_open": "Abrir user.css…",
  "settings.spell_lang": "Idioma del corrector",
  "settings.downloads": "Elegir carpeta de descargas…",
  "settings.export": "Exportar settings.json…",
  "settings.import": "Importar settings.json…",
  "settings.reset_all": "Restablecer todos los ajustes…",
  "settings.sign_out": "Cerrar sesión / borrar la sesión de Messages…",
  "settings.verbose_log": "Escribir registro detallado (main.log)",
  "settings.verbose_log_open": "Abrir main.log…",
  "settings.default_app": "Usar como app de mensajería predeterminada…",
  "settings.os_defaults_win": "Abrir aplicaciones predeterminadas de Windows",
  "settings.os_defaults": "Abrir aplicaciones predeterminadas del sistema",
  "menu.file": "&Archivo",
  "menu.edit": "&Editar",
  "menu.view": "&Ver",
  "menu.window": "&Ventana",
  "menu.help": "&Ayuda",
  "menu.dev": "&Desarrollo",
  "menu.print": "Imprimir…",
  "menu.quit_app": "Salir de Google Messages",
  "menu.quit": "Salir",
  "menu.find": "Buscar",
  "menu.focus_list": "Enfocar la lista de conversaciones",
  "menu.undo": "Deshacer",
  "menu.redo": "Rehacer",
  "menu.cut": "Cortar",
  "menu.copy": "Copiar",
  "menu.paste": "Pegar",
  "menu.select_all": "Seleccionar todo",
  "menu.protocol_tests": "Enlaces de prueba de protocolo…",
  "menu.troubleshooting": "Solución de problemas…",
  "menu.shortcuts": "Atajos de teclado…",
  "menu.whats_new": "Novedades…",
  "menu.open_downloads": "Abrir carpeta de descargas",
  "menu.donate": "Donar por Venmo",
  "menu.learn_more": "Más información",
  "menu.upstream": "Código de OrangeDrangon",
  "menu.updates": "Buscar actualizaciones…",
  "menu.about": "Acerca de Google Messages For Desktop",
  "menu.hide_app": "Ocultar Google Messages",
  "menu.tray_toggle": "Mostrar/ocultar Google Messages",
  "menu.mark_all_read": "Marcar todo como leído",
  "menu.add_dictionary": "Añadir al diccionario",
  "menu.open_link": "Abrir enlace en el navegador",
  "menu.copy_link": "Copiar enlace",
  "menu.reload": "Recargar",
  "menu.dev_tools": "Herramientas de desarrollo",
  "dialog.export_settings": "Exportar ajustes",
  "dialog.import_settings": "Importar ajustes",
  "dialog.reset_settings": "¿Restablecer todos los ajustes, incluidas las banderas de primer uso?",
  "dialog.sign_out": "¿Cerrar sesión y borrar la sesión de Messages en este equipo?",
  "dialog.close_title": "Google Messages",
  "dialog.close_message": "¿Seguir en la bandeja o salir?",
  "dialog.close_tray": "Minimizar a la bandeja",
  "dialog.close_quit": "Salir",
  "dialog.close_remember": "Recordar esta elección",
  "dialog.calls_media":
    "Google Calls quiere usar la cámara y el micrófono. Permítalo solo si está en una llamada.",
  "dialog.calls_detail":
    "Este contenedor no envía cámara, micrófono ni captura de pantalla a ningún sitio salvo a la web de Messages.",
  "dialog.calls_share":
    "¿Permitir compartir pantalla para Google Calls? Solo mientras la llamada esté en esta página.",
  "dialog.block": "Bloquear",
  "dialog.allow": "Permitir",
  "dialog.cancel": "Cancelar",
  "dialog.reset_relaunch": "Restablecer y reiniciar",
  "dialog.sign_out_btn": "Cerrar sesión",
  "dialog.download_location": "Ubicación de descargas",
  "update.available.title": "Actualización disponible",
  "update.available.message": "La versión {latest} está en GitHub.",
  "update.install": "Instalar",
  "update.later": "Más tarde",
  "update.current.title": "Está actualizado",
  "update.current.message": "La última versión en GitHub es {latest}.",
  "update.failed.title": "No se pudieron buscar actualizaciones",
  "update.failed.message": "No hay una versión reciente de GitHub disponible.",
  "update.open_releases": "Abrir la página de versiones",
  "update.dismiss": "Cerrar",
  "donate.title": "El desarrollo continúa",
  "donate.not_now": "Ahora no",
  "about.tagline": "Messages para la web, como aplicación de escritorio.",
  "about.foss": "FOSS con licencia MIT. Este contenedor no rastrea.",
  "about.disclaimer": "No afiliado a Google. Android es una marca de Google LLC.",
  "about.donate": "Donar por Venmo",
  "feedback.bug": "Informar de un error",
  "feedback.feature": "Pedir una función",
};
