import { catalogEs } from "./catalogEs.ts";
import { localizedCatalog } from "./i18n.ts";

export const menuCopyEn = {
  "menu.file": "&File",
  "menu.edit": "&Edit",
  "menu.view": "&View",
  "menu.window": "&Window",
  "menu.help": "&Help",
  "menu.dev": "&Development",
  "menu.print": "Print…",
  "menu.quit_app": "Quit Google Messages",
  "menu.quit": "Quit",
  "menu.find": "Find",
  "menu.focus_list": "Focus conversation list",
  "menu.undo": "Undo",
  "menu.redo": "Redo",
  "menu.cut": "Cut",
  "menu.copy": "Copy",
  "menu.paste": "Paste",
  "menu.select_all": "Select All",
  "menu.protocol_tests": "Protocol Test Links…",
  "menu.troubleshooting": "Troubleshooting…",
  "menu.shortcuts": "Keyboard Shortcuts…",
  "menu.whats_new": "What’s New…",
  "menu.open_downloads": "Open downloads folder",
  "menu.donate": "Donate via Venmo",
  "menu.learn_more": "Learn More",
  "menu.upstream": "OrangeDrangon Upstream",
  "menu.updates": "Check for Updates…",
  "menu.about": "About Google Messages For Desktop",
  "menu.hide_app": "Hide Google Messages",
  "menu.tray_toggle": "Show/Hide Google Messages",
  "menu.mark_all_read": "Mark all as read",
  "menu.add_dictionary": "Add to Dictionary",
  "menu.open_link": "Open link in browser",
  "menu.copy_link": "Copy link",
  "menu.reload": "Reload",
  "menu.dev_tools": "Development Tools",
  "dialog.export_settings": "Export settings",
  "dialog.import_settings": "Import settings",
  "dialog.reset_settings": "Reset all settings, including first-run flags?",
  "dialog.sign_out": "Sign out and clear the Messages session on this computer?",
  "dialog.close_title": "Google Messages",
  "dialog.close_message": "Keep running in the tray, or quit?",
  "dialog.close_tray": "Minimize to tray",
  "dialog.close_quit": "Quit",
  "dialog.close_remember": "Remember this choice",
  "dialog.calls_media":
    "Google Calls wants the camera and microphone on this computer. Allow only if you are placing or answering a call.",
  "dialog.calls_detail":
    "This wrapper does not send camera, microphone, or screen share anywhere except the Messages web app.",
  "dialog.calls_share":
    "Allow screen share for Google Calls? Only while a call is on this page.",
  "dialog.block": "Block",
  "dialog.allow": "Allow",
  "dialog.cancel": "Cancel",
  "dialog.reset_relaunch": "Reset and relaunch",
  "dialog.sign_out_btn": "Sign out",
  "dialog.download_location": "Download location",
  "update.available.title": "Update available",
  "update.available.message": "Version {latest} is available on GitHub.",
  "update.install": "Install",
  "update.later": "Later",
  "update.current.title": "You're up to date",
  "update.current.message": "GitHub latest is {latest}.",
  "update.failed.title": "Could not check for updates",
  "update.failed.message": "GitHub latest release is unavailable.",
  "update.open_releases": "Open releases page",
  "update.dismiss": "Dismiss",
  "donate.title": "Development is still going",
  "donate.not_now": "Not now",
};

export const menuCopy = localizedCatalog(menuCopyEn, catalogEs);
