import { catalogEs } from "./catalogEs.ts";
import { localizedCatalog } from "./i18n.ts";

const settingsCopyEn = {
  "settings.title": "&Settings",
  "settings.title_mac": "&Preferences",
  "settings.theme": "Appearance",
  "settings.theme.system": "System",
  "settings.theme.light": "Light",
  "settings.theme.dark": "Dark",
  "settings.density": "Density",
  "settings.density.default": "Default",
  "settings.density.comfortable": "Comfortable",
  "settings.density.compact": "Compact",
  "settings.custom_tray": "Custom tray icon (PNG)…",
  "settings.custom_tray_clear": "Use built-in tray icon",
  "settings.badge_color": "Unread badge color",
  "settings.badge_red": "Red",
  "settings.badge_accent": "Accent (no red overlay)",
  "settings.mica": "Windows 11 Mica titlebar (restart)",
  "settings.mute_hotkey": "Global mute hotkey (Ctrl+Shift+M)",
  "settings.profile": "Account profile (restart)",
  "settings.profile.main": "Main",
  "settings.profile.work": "Work",
  "settings.profile.personal": "Personal",
  "settings.profile.guest": "Guest (wiped on quit)",
  "settings.snippet_copy_1": "Copy snippet 1",
  "settings.snippet_copy_2": "Copy snippet 2",
  "settings.snippet_copy_3": "Copy snippet 3",
  "settings.snippet_save_1": "Save clipboard as snippet 1",
  "settings.snippet_save_2": "Save clipboard as snippet 2",
  "settings.snippet_save_3": "Save clipboard as snippet 3",
  "settings.signature_save": "Save clipboard as protocol signature",
  "settings.confirm_protocol": "Confirm before protocol compose",
  "settings.mute_toast_clipboard": "Mute OS toasts for clipboard name (not Google mute)",
  "settings.auto_hide_menu": "Auto Hide Menu Bar",
  "settings.tray": "Enable Tray Icon",
  "settings.tray_mac": "Enable Menu Bar Icon",
  "settings.tray_tooltip":
    "Shows Google Messages in the notification area (system tray), near the clock — not the taskbar pin. Minimize to tray to keep the app warm so reopen skips the long cold web load.",
  "settings.start_in_tray": "Start In Tray",
  "settings.start_hidden": "Start Hidden",
  "settings.mono_tray": "Use Monochrome Tray Icon",
  "settings.tray_icons": "Show Icons in Tray Menu",
  "settings.red_dot": "Show Red Dot for Unread Messages",
  "settings.hide_content": "Hide Notification Content",
  "settings.notify_sound": "Notification sound",
  "settings.quiet_hours": "Quiet hours",
  "settings.quiet_hours.off": "Off",
  "settings.quiet_hours.22_07": "10:00 PM – 7:00 AM",
  "settings.quiet_hours.21_08": "9:00 PM – 8:00 AM",
  "settings.quiet_hours.23_06": "11:00 PM – 6:00 AM",
  "settings.always_on_top": "Always on top",
  "settings.reduce_motion": "Reduce motion (no taskbar flash)",
  "settings.close_behavior": "When closing the window",
  "settings.close_ask": "Ask every time",
  "settings.close_tray": "Minimize to tray",
  "settings.close_quit": "Quit the app",
  "settings.hw_accel":
    "Hardware acceleration (restart required) — keep on; turning it off slows Google Messages a lot",
  "settings.reset_window": "Reset window size and position",
  "settings.taskbar_flash": "Taskbar Flash on New Message",
  "settings.spellcheck": "Enable Spell Checking",
  "settings.save_crashes": "Save crash details for me to review",
  "settings.check_updates_launch": "Check for updates on launch",
  "settings.start_with_os": "Start with the operating system",
  "settings.user_css": "Load local user.css (never remote)",
  "settings.user_css_open": "Open user.css…",
  "settings.spell_lang": "Spell-check language",
  "settings.downloads": "Choose download folder…",
  "settings.export": "Export settings.json…",
  "settings.import": "Import settings.json…",
  "settings.reset_all": "Reset all settings…",
  "settings.sign_out": "Sign out / clear Messages session…",
  "settings.verbose_log": "Write verbose main-process log (main.log)",
  "settings.verbose_log_open": "Open main.log…",
  "settings.default_app": "Set as Default Messaging App…",
  "settings.os_defaults_win": "Open Windows Default Apps Settings",
  "settings.os_defaults": "Open OS Default Apps Settings",
};

export const settingsCopy = localizedCatalog(settingsCopyEn, catalogEs);
